version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum update
      - sudo yum install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

artifacts:
  files:
    - '**/*'
